# yaml file to store the configurations


# Robot structure parameters
hip_link_length: 0.0605
upper_leg_link_length: 0.11126
lower_leg_link_length: 0.1185 #TODO: include foot length
body_width: 0.078
body_length: 0.2075

# Stance parameters
default_stand_height: 0.17
stand_front_x_offset: -0.020
stand_back_x_offset: -0.02
lie_down_height: 0.083
lie_down_foot_x_offset: 0.065 

#TODO: Servo parameters
num_servos: 12
servo_max_angle_deg: 82.5
RF_3: {num: 9,  center: 306,range: 385,direction:  1, center_angle_deg:  99.86}
RF_2: {num: 8,  center: 306,range: 407,direction:  1, center_angle_deg: -31.62}
RF_1: {num: 7,  center: 306,range: 396,direction:  -1, center_angle_deg:  1.67}
RB_3: {num: 3,  center: 306,range: 369,direction:  1, center_angle_deg:  95.37}
RB_2: {num: 2,  center: 306,range: 381,direction:  1, center_angle_deg: -37.21}
RB_1: {num: 1,  center: 306,range: 403,direction:  1, center_angle_deg:  -3.27}
LB_3: {num: 6,  center: 306,range: 374,direction:  1, center_angle_deg: -92.65}
LB_2: {num: 5,  center: 306,range: 403,direction:  1, center_angle_deg:  91.23}
LB_1: {num: 4,  center: 306,range: 367,direction:  -1, center_angle_deg:  -7.20}
LF_3: {num: 12, center: 306,range: 385,direction:  1, center_angle_deg: -87.43}
LF_2: {num: 11, center: 306,range: 388,direction:  1, center_angle_deg:  38.21}
LF_1: {num: 10, center: 306,range: 388,direction:  1, center_angle_deg:  4.67}

# Control Parameters
transit_tau: 0.3 # Time constant in seconds for transition state first order filters
transit_rl: 0.06 # rate limit in m/s for transition state first order filters
transit_angle_rl: 0.35 # rate limit in rad/s for transition angle state first order filters

# Gait parameters
max_fwd_velocity: 0.4
max_side_velocity: 0.4
max_yaw_rate: 0.35
z_clearance: 0.045
alpha: 0.5
beta: 0.5
num_phases: 4
rb_contact_phases: [1, 0, 1, 1]
rf_contact_phases: [1, 1, 1, 0]
lf_contact_phases: [1, 0, 1, 1]
lb_contact_phases: [1, 1, 1, 0]
overlap_time: 0.2
swing_time: 0.20
foot_height_time_constant: 0.02
body_shift_phases: [0, 0, 0, 0]
fwd_body_balance_shift: 0.00
back_body_balance_shift: 0.00
side_body_balance_shift: 0.0

# Node parameters
dt: 0.02 #50 hz

# Debug mode
debug_mode: false
plot_mode: true